<?php

/**
 * This file is part of Vulkan package.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace Bic\Vulkan\Enum;

final class VkAccelerationStructureTypeKHR
{
    public const VK_ACCELERATION_STRUCTURE_TYPE_TOP_LEVEL_KHR = 0;
    public const VK_ACCELERATION_STRUCTURE_TYPE_BOTTOM_LEVEL_KHR = 1;
    public const VK_ACCELERATION_STRUCTURE_TYPE_TOP_LEVEL_NV = self::VK_ACCELERATION_STRUCTURE_TYPE_TOP_LEVEL_KHR;
    public const VK_ACCELERATION_STRUCTURE_TYPE_BOTTOM_LEVEL_NV = self::VK_ACCELERATION_STRUCTURE_TYPE_BOTTOM_LEVEL_KHR;
    public const VK_ACCELERATION_STRUCTURE_TYPE_BEGIN_RANGE_KHR = self::VK_ACCELERATION_STRUCTURE_TYPE_TOP_LEVEL_KHR;
    public const VK_ACCELERATION_STRUCTURE_TYPE_END_RANGE_KHR = self::VK_ACCELERATION_STRUCTURE_TYPE_BOTTOM_LEVEL_KHR;
    public const VK_ACCELERATION_STRUCTURE_TYPE_RANGE_SIZE_KHR = self::VK_ACCELERATION_STRUCTURE_TYPE_BOTTOM_LEVEL_KHR - self::VK_ACCELERATION_STRUCTURE_TYPE_TOP_LEVEL_KHR + 1;
    public const VK_ACCELERATION_STRUCTURE_TYPE_MAX_ENUM_KHR = 0x7FFFFFFF;
}
