<?php

/**
 * This file is part of Vulkan package.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace Bic\Vulkan\Enum;

final class VkCopyAccelerationStructureModeKHR
{
    public const VK_COPY_ACCELERATION_STRUCTURE_MODE_CLONE_KHR = 0;
    public const VK_COPY_ACCELERATION_STRUCTURE_MODE_COMPACT_KHR = 1;
    public const VK_COPY_ACCELERATION_STRUCTURE_MODE_SERIALIZE_KHR = 2;
    public const VK_COPY_ACCELERATION_STRUCTURE_MODE_DESERIALIZE_KHR = 3;
    public const VK_COPY_ACCELERATION_STRUCTURE_MODE_CLONE_NV = self::VK_COPY_ACCELERATION_STRUCTURE_MODE_CLONE_KHR;
    public const VK_COPY_ACCELERATION_STRUCTURE_MODE_COMPACT_NV = self::VK_COPY_ACCELERATION_STRUCTURE_MODE_COMPACT_KHR;
    public const VK_COPY_ACCELERATION_STRUCTURE_MODE_BEGIN_RANGE_KHR = self::VK_COPY_ACCELERATION_STRUCTURE_MODE_CLONE_KHR;
    public const VK_COPY_ACCELERATION_STRUCTURE_MODE_END_RANGE_KHR = self::VK_COPY_ACCELERATION_STRUCTURE_MODE_DESERIALIZE_KHR;
    public const VK_COPY_ACCELERATION_STRUCTURE_MODE_RANGE_SIZE_KHR = self::VK_COPY_ACCELERATION_STRUCTURE_MODE_DESERIALIZE_KHR - self::VK_COPY_ACCELERATION_STRUCTURE_MODE_CLONE_KHR + 1;
    public const VK_COPY_ACCELERATION_STRUCTURE_MODE_MAX_ENUM_KHR = 0x7FFFFFFF;
}
