<?php

/**
 * This file is part of BicEngine package.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace Bic\Vulkan\Enum;

final class VkPerformanceCounterScopeKHR
{
    public const VK_PERFORMANCE_COUNTER_SCOPE_COMMAND_BUFFER_KHR = 0;
    public const VK_PERFORMANCE_COUNTER_SCOPE_RENDER_PASS_KHR = 1;
    public const VK_PERFORMANCE_COUNTER_SCOPE_COMMAND_KHR = 2;
    public const VK_QUERY_SCOPE_COMMAND_BUFFER_KHR = self::VK_PERFORMANCE_COUNTER_SCOPE_COMMAND_BUFFER_KHR;
    public const VK_QUERY_SCOPE_RENDER_PASS_KHR = self::VK_PERFORMANCE_COUNTER_SCOPE_RENDER_PASS_KHR;
    public const VK_QUERY_SCOPE_COMMAND_KHR = self::VK_PERFORMANCE_COUNTER_SCOPE_COMMAND_KHR;
    public const VK_PERFORMANCE_COUNTER_SCOPE_BEGIN_RANGE_KHR = self::VK_PERFORMANCE_COUNTER_SCOPE_COMMAND_BUFFER_KHR;
    public const VK_PERFORMANCE_COUNTER_SCOPE_END_RANGE_KHR = self::VK_PERFORMANCE_COUNTER_SCOPE_COMMAND_KHR;
    public const VK_PERFORMANCE_COUNTER_SCOPE_RANGE_SIZE_KHR = self::VK_PERFORMANCE_COUNTER_SCOPE_COMMAND_KHR - self::VK_PERFORMANCE_COUNTER_SCOPE_COMMAND_BUFFER_KHR + 1;
    public const VK_PERFORMANCE_COUNTER_SCOPE_MAX_ENUM_KHR = 0x7FFFFFFF;
}
