<?php

/**
 * This file is part of Vulkan package.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace Bic\Vulkan\Enum;

/**
 * @since 1.2
 */
final class VkShaderFloatControlsIndependence
{
    public const VK_SHADER_FLOAT_CONTROLS_INDEPENDENCE_32_BIT_ONLY = 0;
    public const VK_SHADER_FLOAT_CONTROLS_INDEPENDENCE_ALL = 1;
    public const VK_SHADER_FLOAT_CONTROLS_INDEPENDENCE_NONE = 2;
    public const VK_SHADER_FLOAT_CONTROLS_INDEPENDENCE_32_BIT_ONLY_KHR = self::VK_SHADER_FLOAT_CONTROLS_INDEPENDENCE_32_BIT_ONLY;
    public const VK_SHADER_FLOAT_CONTROLS_INDEPENDENCE_ALL_KHR = self::VK_SHADER_FLOAT_CONTROLS_INDEPENDENCE_ALL;
    public const VK_SHADER_FLOAT_CONTROLS_INDEPENDENCE_NONE_KHR = self::VK_SHADER_FLOAT_CONTROLS_INDEPENDENCE_NONE;
    public const VK_SHADER_FLOAT_CONTROLS_INDEPENDENCE_BEGIN_RANGE = self::VK_SHADER_FLOAT_CONTROLS_INDEPENDENCE_32_BIT_ONLY;
    public const VK_SHADER_FLOAT_CONTROLS_INDEPENDENCE_END_RANGE = self::VK_SHADER_FLOAT_CONTROLS_INDEPENDENCE_NONE;
    public const VK_SHADER_FLOAT_CONTROLS_INDEPENDENCE_RANGE_SIZE = self::VK_SHADER_FLOAT_CONTROLS_INDEPENDENCE_NONE - self::VK_SHADER_FLOAT_CONTROLS_INDEPENDENCE_32_BIT_ONLY + 1;
    public const VK_SHADER_FLOAT_CONTROLS_INDEPENDENCE_MAX_ENUM = 0x7FFFFFFF;
}
