<?php

/**
 * This file is part of BicEngine package.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace Bic\Vulkan;

final class VkColorSpaceKHR
{
    public const VK_COLOR_SPACE_SRGB_NONLINEAR_KHR = 0;
    public const VK_COLOR_SPACE_DISPLAY_P3_NONLINEAR_EXT = 1000104001;
    public const VK_COLOR_SPACE_EXTENDED_SRGB_LINEAR_EXT = 1000104002;
    public const VK_COLOR_SPACE_DISPLAY_P3_LINEAR_EXT = 1000104003;
    public const VK_COLOR_SPACE_DCI_P3_NONLINEAR_EXT = 1000104004;
    public const VK_COLOR_SPACE_BT709_LINEAR_EXT = 1000104005;
    public const VK_COLOR_SPACE_BT709_NONLINEAR_EXT = 1000104006;
    public const VK_COLOR_SPACE_BT2020_LINEAR_EXT = 1000104007;
    public const VK_COLOR_SPACE_HDR10_ST2084_EXT = 1000104008;
    public const VK_COLOR_SPACE_DOLBYVISION_EXT = 1000104009;
    public const VK_COLOR_SPACE_HDR10_HLG_EXT = 1000104010;
    public const VK_COLOR_SPACE_ADOBERGB_LINEAR_EXT = 1000104011;
    public const VK_COLOR_SPACE_ADOBERGB_NONLINEAR_EXT = 1000104012;
    public const VK_COLOR_SPACE_PASS_THROUGH_EXT = 1000104013;
    public const VK_COLOR_SPACE_EXTENDED_SRGB_NONLINEAR_EXT = 1000104014;
    public const VK_COLOR_SPACE_DISPLAY_NATIVE_AMD = 1000213000;
    public const VK_COLORSPACE_SRGB_NONLINEAR_KHR = self::VK_COLOR_SPACE_SRGB_NONLINEAR_KHR;
    public const VK_COLOR_SPACE_DCI_P3_LINEAR_EXT = self::VK_COLOR_SPACE_DISPLAY_P3_LINEAR_EXT;
    public const VK_COLOR_SPACE_BEGIN_RANGE_KHR = self::VK_COLOR_SPACE_SRGB_NONLINEAR_KHR;
    public const VK_COLOR_SPACE_END_RANGE_KHR = self::VK_COLOR_SPACE_SRGB_NONLINEAR_KHR;
    public const VK_COLOR_SPACE_RANGE_SIZE_KHR = self::VK_COLOR_SPACE_SRGB_NONLINEAR_KHR - self::VK_COLOR_SPACE_SRGB_NONLINEAR_KHR + 1;
    public const VK_COLOR_SPACE_MAX_ENUM_KHR = 0x7FFFFFFF;
}
