<?php

/**
 * This file is part of BicEngine package.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace Bic\Vulkan\Enum;

/**
 * @since 1.2
 */
final class VkDescriptorBindingFlagBits
{
    public const VK_DESCRIPTOR_BINDING_UPDATE_AFTER_BIND_BIT = 0x00000001;
    public const VK_DESCRIPTOR_BINDING_UPDATE_UNUSED_WHILE_PENDING_BIT = 0x00000002;
    public const VK_DESCRIPTOR_BINDING_PARTIALLY_BOUND_BIT = 0x00000004;
    public const VK_DESCRIPTOR_BINDING_VARIABLE_DESCRIPTOR_COUNT_BIT = 0x00000008;
    public const VK_DESCRIPTOR_BINDING_UPDATE_AFTER_BIND_BIT_EXT = self::VK_DESCRIPTOR_BINDING_UPDATE_AFTER_BIND_BIT;
    public const VK_DESCRIPTOR_BINDING_UPDATE_UNUSED_WHILE_PENDING_BIT_EXT = self::VK_DESCRIPTOR_BINDING_UPDATE_UNUSED_WHILE_PENDING_BIT;
    public const VK_DESCRIPTOR_BINDING_PARTIALLY_BOUND_BIT_EXT = self::VK_DESCRIPTOR_BINDING_PARTIALLY_BOUND_BIT;
    public const VK_DESCRIPTOR_BINDING_VARIABLE_DESCRIPTOR_COUNT_BIT_EXT = self::VK_DESCRIPTOR_BINDING_VARIABLE_DESCRIPTOR_COUNT_BIT;
    public const VK_DESCRIPTOR_BINDING_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF;
}
