<?php

/**
 * This file is part of BicEngine package.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace Bic\Vulkan;

final class VkDebugReportObjectTypeEXT
{
    public const VK_DEBUG_REPORT_OBJECT_TYPE_UNKNOWN_EXT = 0;
    public const VK_DEBUG_REPORT_OBJECT_TYPE_INSTANCE_EXT = 1;
    public const VK_DEBUG_REPORT_OBJECT_TYPE_PHYSICAL_DEVICE_EXT = 2;
    public const VK_DEBUG_REPORT_OBJECT_TYPE_DEVICE_EXT = 3;
    public const VK_DEBUG_REPORT_OBJECT_TYPE_QUEUE_EXT = 4;
    public const VK_DEBUG_REPORT_OBJECT_TYPE_SEMAPHORE_EXT = 5;
    public const VK_DEBUG_REPORT_OBJECT_TYPE_COMMAND_BUFFER_EXT = 6;
    public const VK_DEBUG_REPORT_OBJECT_TYPE_FENCE_EXT = 7;
    public const VK_DEBUG_REPORT_OBJECT_TYPE_DEVICE_MEMORY_EXT = 8;
    public const VK_DEBUG_REPORT_OBJECT_TYPE_BUFFER_EXT = 9;
    public const VK_DEBUG_REPORT_OBJECT_TYPE_IMAGE_EXT = 10;
    public const VK_DEBUG_REPORT_OBJECT_TYPE_EVENT_EXT = 11;
    public const VK_DEBUG_REPORT_OBJECT_TYPE_QUERY_POOL_EXT = 12;
    public const VK_DEBUG_REPORT_OBJECT_TYPE_BUFFER_VIEW_EXT = 13;
    public const VK_DEBUG_REPORT_OBJECT_TYPE_IMAGE_VIEW_EXT = 14;
    public const VK_DEBUG_REPORT_OBJECT_TYPE_SHADER_MODULE_EXT = 15;
    public const VK_DEBUG_REPORT_OBJECT_TYPE_PIPELINE_CACHE_EXT = 16;
    public const VK_DEBUG_REPORT_OBJECT_TYPE_PIPELINE_LAYOUT_EXT = 17;
    public const VK_DEBUG_REPORT_OBJECT_TYPE_RENDER_PASS_EXT = 18;
    public const VK_DEBUG_REPORT_OBJECT_TYPE_PIPELINE_EXT = 19;
    public const VK_DEBUG_REPORT_OBJECT_TYPE_DESCRIPTOR_SET_LAYOUT_EXT = 20;
    public const VK_DEBUG_REPORT_OBJECT_TYPE_SAMPLER_EXT = 21;
    public const VK_DEBUG_REPORT_OBJECT_TYPE_DESCRIPTOR_POOL_EXT = 22;
    public const VK_DEBUG_REPORT_OBJECT_TYPE_DESCRIPTOR_SET_EXT = 23;
    public const VK_DEBUG_REPORT_OBJECT_TYPE_FRAMEBUFFER_EXT = 24;
    public const VK_DEBUG_REPORT_OBJECT_TYPE_COMMAND_POOL_EXT = 25;
    public const VK_DEBUG_REPORT_OBJECT_TYPE_SURFACE_KHR_EXT = 26;
    public const VK_DEBUG_REPORT_OBJECT_TYPE_SWAPCHAIN_KHR_EXT = 27;
    public const VK_DEBUG_REPORT_OBJECT_TYPE_DEBUG_REPORT_CALLBACK_EXT_EXT = 28;
    public const VK_DEBUG_REPORT_OBJECT_TYPE_DISPLAY_KHR_EXT = 29;
    public const VK_DEBUG_REPORT_OBJECT_TYPE_DISPLAY_MODE_KHR_EXT = 30;
    public const VK_DEBUG_REPORT_OBJECT_TYPE_VALIDATION_CACHE_EXT_EXT = 33;
    public const VK_DEBUG_REPORT_OBJECT_TYPE_SAMPLER_YCBCR_CONVERSION_EXT = 1000156000;
    public const VK_DEBUG_REPORT_OBJECT_TYPE_DESCRIPTOR_UPDATE_TEMPLATE_EXT = 1000085000;
    public const VK_DEBUG_REPORT_OBJECT_TYPE_ACCELERATION_STRUCTURE_KHR_EXT = 1000165000;
    public const VK_DEBUG_REPORT_OBJECT_TYPE_DEBUG_REPORT_EXT = self::VK_DEBUG_REPORT_OBJECT_TYPE_DEBUG_REPORT_CALLBACK_EXT_EXT;
    public const VK_DEBUG_REPORT_OBJECT_TYPE_VALIDATION_CACHE_EXT = self::VK_DEBUG_REPORT_OBJECT_TYPE_VALIDATION_CACHE_EXT_EXT;
    public const VK_DEBUG_REPORT_OBJECT_TYPE_DESCRIPTOR_UPDATE_TEMPLATE_KHR_EXT = self::VK_DEBUG_REPORT_OBJECT_TYPE_DESCRIPTOR_UPDATE_TEMPLATE_EXT;
    public const VK_DEBUG_REPORT_OBJECT_TYPE_SAMPLER_YCBCR_CONVERSION_KHR_EXT = self::VK_DEBUG_REPORT_OBJECT_TYPE_SAMPLER_YCBCR_CONVERSION_EXT;
    public const VK_DEBUG_REPORT_OBJECT_TYPE_ACCELERATION_STRUCTURE_NV_EXT = self::VK_DEBUG_REPORT_OBJECT_TYPE_ACCELERATION_STRUCTURE_KHR_EXT;
    public const VK_DEBUG_REPORT_OBJECT_TYPE_BEGIN_RANGE_EXT = self::VK_DEBUG_REPORT_OBJECT_TYPE_UNKNOWN_EXT;
    public const VK_DEBUG_REPORT_OBJECT_TYPE_END_RANGE_EXT = self::VK_DEBUG_REPORT_OBJECT_TYPE_VALIDATION_CACHE_EXT_EXT;
    public const VK_DEBUG_REPORT_OBJECT_TYPE_RANGE_SIZE_EXT = self::VK_DEBUG_REPORT_OBJECT_TYPE_VALIDATION_CACHE_EXT_EXT - self::VK_DEBUG_REPORT_OBJECT_TYPE_UNKNOWN_EXT + 1;
    public const VK_DEBUG_REPORT_OBJECT_TYPE_MAX_ENUM_EXT = 0x7FFFFFFF;
}
