<?php

/**
 * This file is part of BicEngine package.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace Bic\Vulkan;

/**
 * @since 1.0
 */
final class VkImageLayout
{
    public const VK_IMAGE_LAYOUT_UNDEFINED = 0;
    public const VK_IMAGE_LAYOUT_GENERAL = 1;
    public const VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL = 2;
    public const VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL = 3;
    public const VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL = 4;
    public const VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL = 5;
    public const VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL = 6;
    public const VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL = 7;
    public const VK_IMAGE_LAYOUT_PREINITIALIZED = 8;
    public const VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_STENCIL_ATTACHMENT_OPTIMAL = 1000117000;
    public const VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_STENCIL_READ_ONLY_OPTIMAL = 1000117001;
    public const VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_OPTIMAL = 1000241000;
    public const VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_OPTIMAL = 1000241001;
    public const VK_IMAGE_LAYOUT_STENCIL_ATTACHMENT_OPTIMAL = 1000241002;
    public const VK_IMAGE_LAYOUT_STENCIL_READ_ONLY_OPTIMAL = 1000241003;
    public const VK_IMAGE_LAYOUT_PRESENT_SRC_KHR = 1000001002;
    public const VK_IMAGE_LAYOUT_SHARED_PRESENT_KHR = 1000111000;
    public const VK_IMAGE_LAYOUT_SHADING_RATE_OPTIMAL_NV = 1000164003;
    public const VK_IMAGE_LAYOUT_FRAGMENT_DENSITY_MAP_OPTIMAL_EXT = 1000218000;
    public const VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_STENCIL_ATTACHMENT_OPTIMAL_KHR = self::VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_STENCIL_ATTACHMENT_OPTIMAL;
    public const VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_STENCIL_READ_ONLY_OPTIMAL_KHR = self::VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_STENCIL_READ_ONLY_OPTIMAL;
    public const VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_OPTIMAL_KHR = self::VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_OPTIMAL;
    public const VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_OPTIMAL_KHR = self::VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_OPTIMAL;
    public const VK_IMAGE_LAYOUT_STENCIL_ATTACHMENT_OPTIMAL_KHR = self::VK_IMAGE_LAYOUT_STENCIL_ATTACHMENT_OPTIMAL;
    public const VK_IMAGE_LAYOUT_STENCIL_READ_ONLY_OPTIMAL_KHR = self::VK_IMAGE_LAYOUT_STENCIL_READ_ONLY_OPTIMAL;
    public const VK_IMAGE_LAYOUT_BEGIN_RANGE = self::VK_IMAGE_LAYOUT_UNDEFINED;
    public const VK_IMAGE_LAYOUT_END_RANGE = self::VK_IMAGE_LAYOUT_PREINITIALIZED;
    public const VK_IMAGE_LAYOUT_RANGE_SIZE = self::VK_IMAGE_LAYOUT_PREINITIALIZED - self::VK_IMAGE_LAYOUT_UNDEFINED + 1;
    public const VK_IMAGE_LAYOUT_MAX_ENUM = 0x7FFFFFFF;
}
