<?php

/**
 * This file is part of BicEngine package.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace Bic\Vulkan\Enum;

final class VkRayTracingShaderGroupTypeKHR
{
    public const VK_RAY_TRACING_SHADER_GROUP_TYPE_GENERAL_KHR = 0;
    public const VK_RAY_TRACING_SHADER_GROUP_TYPE_TRIANGLES_HIT_GROUP_KHR = 1;
    public const VK_RAY_TRACING_SHADER_GROUP_TYPE_PROCEDURAL_HIT_GROUP_KHR = 2;
    public const VK_RAY_TRACING_SHADER_GROUP_TYPE_GENERAL_NV = self::VK_RAY_TRACING_SHADER_GROUP_TYPE_GENERAL_KHR;
    public const VK_RAY_TRACING_SHADER_GROUP_TYPE_TRIANGLES_HIT_GROUP_NV = self::VK_RAY_TRACING_SHADER_GROUP_TYPE_TRIANGLES_HIT_GROUP_KHR;
    public const VK_RAY_TRACING_SHADER_GROUP_TYPE_PROCEDURAL_HIT_GROUP_NV = self::VK_RAY_TRACING_SHADER_GROUP_TYPE_PROCEDURAL_HIT_GROUP_KHR;
    public const VK_RAY_TRACING_SHADER_GROUP_TYPE_BEGIN_RANGE_KHR = self::VK_RAY_TRACING_SHADER_GROUP_TYPE_GENERAL_KHR;
    public const VK_RAY_TRACING_SHADER_GROUP_TYPE_END_RANGE_KHR = self::VK_RAY_TRACING_SHADER_GROUP_TYPE_PROCEDURAL_HIT_GROUP_KHR;
    public const VK_RAY_TRACING_SHADER_GROUP_TYPE_RANGE_SIZE_KHR = self::VK_RAY_TRACING_SHADER_GROUP_TYPE_PROCEDURAL_HIT_GROUP_KHR - self::VK_RAY_TRACING_SHADER_GROUP_TYPE_GENERAL_KHR + 1;
    public const VK_RAY_TRACING_SHADER_GROUP_TYPE_MAX_ENUM_KHR = 0x7FFFFFFF;
}
